language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8
install:
  - gem install cocoapods --pre
before_script:
  - rm -rf ~/Library/Developer/Xcode/DerivedData
script:
  - pod update
  - pod lib lint --allow-warnings
  - carthage update
  - xcodebuild -workspace BMSPush.xcworkspace -scheme 'BMSPush' clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO
  - xcodebuild -workspace BMSPush.xcworkspace test -scheme 'BMSPushTests' -destination 'platform=iOS Simulator,name=iPhone 6s'
